  version: 2.1
  jobs:
    build:
      docker: 
        - image: circleci/node:12.8.1 # the primary container, where your job's commands are run
      steps:
        - checkout # check out the code in the project directory
        - run: npm run setup && npm test
